### ISSUE TITLE
example

### ISSUE THREAD

**Issue by Arthur-Koo** [dermotduffy/hyperion-py#1]
Hello, could you provide some set-value samples? thanks!

**Comment by dermotduffy** [comment]
Hello @Arthur-Koo , thanks for the bug report. I think you mean provide an example in the README of a "set" call, rather than just read calls. Is that correct?

**Comment by Arthur-Koo** [comment]
Exactly, thanks!

**Comment by Arthur-Koo** [comment]
Actually I've tried to send JSON command directly, but there are issues on instance. The guidance for instance start/stop/switch doesn't work. I can use component operation to start/stop instance instead. So I'd like to know is there any way in ur solution to resolve instance switch issue. And I hope to get the idea to do something unofficially such as LED hardware update. Thanks!

**Comment by Arthur-Koo** [comment]
Thanks!
