### ISSUE TITLE
Error doing job: Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by starkillerOG** [dermotduffy/hyperion-py#4]
As discussed here: https://github.com/home-assistant/core/issues/45289, there is some issue with async tasks.
I will copy the posts from the other issue mentioned above to have all info in one place.

**Comment by starkillerOG** [comment]
On a side note, I have been seeing these (not very discriptive) errors in my HomeAssistant log:
`ERROR (Recorder) [homeassistant] Error doing job: Task was destroyed but it is pending!`
I am trying to figure out where they are coming from and today when I ran a test script from hyperion I got a simular errors.

The script is this:
```
#!/usr/bin/python
"""Simple Hyperion client read demonstration."""

import asyncio
from hyperion import client, const

HOST = "192.168.1.IP"


async def print_brightness():
    """Print Hyperion brightness."""

    hyperion_client = client.HyperionClient(HOST)
    if not await hyperion_client.async_client_connect():
        print("fail")
        return
    print("Brightness: %i%%" % hyperion_client.adjustment[0][const.KEY_BRIGHTNESS])


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(print_brightness())
```

When I run this in command line on a windows 10 PC with python3 I got:
```
Brightness: 100%
Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<HyperionClient._maintenance_task_loop() done, defined at ....\Python3\lib\site-packages\hyperion\client.py:423> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0300F940>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<HyperionClient._receive_task_loop() running at ...\Python3\lib\site-packages\hyperion\client.py:456> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0300F8E0>()]>>
```

These errors look very simular, so I have the feeling the errors in HomeAssistant are caused by the Hyperion Integration somewhere.
Have you ever noticed these errors?

**Comment by starkillerOG** [comment]
> I have tested some more and when I remove my Hyperion integration indeed the `ERROR (Recorder) [homeassistant] Error doing job: Task was destroyed but it is pending!` go away.
> I always have this error 2x when I restart HomeAssistant (I now also have 2 Hyperion entities).
> 
> So I am pretty convinced this is caused by the Hyperion Integration.
> Schould I make a seprate issue for that, or can that be discussed in this issue?
> 
> That error has to do with async stuff and I know very little about it, no idea if it is serious and could really cause issues...
> I have noticed that my HomeAssistant somtimes "hangs", it starts loading all integrations, and then nothing happens for about 2-3 minutes and then it continues and loads the rest and starts up. sometimes it starts up really quickly and sometimes it does this "hanging" for 2-3 minutes. It might be related, not sure.....
> Anyway I consistantly see this error 2x when starting HomeAssistant, but it never re-appears as long as you do not restart/reboot.
> So my guess is that it is something in the connect function of Hyperion.

**Comment by starkillerOG** [comment]
> Thanks . I do have those log entries although hadn't made the mental leap from that non-descriptive error message to Hyperion. It's possible the underlying hyperion-py library is leaking async tasks on start-up or failing to correctly clean them up.
> 
> Would you mind filing an issue here: https://github.com/dermotduffy/hyperion-py/issues
> 
> I will investigate that. I highly doubt it is anything related to your change/issue here, nor indicative of anything serious, so I'd suggest you entirely ignore it and you can follow along on the issue you file above?
> 
> Thanks.

**Comment by starkillerOG** [comment]
Some aditional info:
I have 3 hyperion instances on one server.
I had 2 of them in HomeAssistant and 1 of them disabled in HomeAssistant, then I saw those errors.

Now I have enabled all 3 instances in HomeAssistant and it seems like the errors have disapeard.
So it might also be related to disabled hyperion entities in HomeAssistant, but could just be coincidence....

**Comment by dermotduffy** [comment]
Thank you -- will investigate.

**Comment by dermotduffy** [comment]
Small update: The example emits this error when `async_client_disconnect()` is not called prior to the program exiting. I've updated the README to include disconnect calls. That does not explain the Home Assistant issue.

**Comment by dermotduffy** [comment]
Current theory: When the Hyperion client is connected, it creates an async maintenance tasks that sits there waiting for the connection to be  dropped and attempts to re-establish it. If the client is connected, but then destroyed before being disconnected -- this maintenance task is left pending and this log message is emitted. There's not much about this that can be done in hyperion-py, as it indicates that someone has connected and destroyed the client without disconnecting (and I cannot reliably clean up async tasks in a destructor).

I found this can happen in Home Assistant in error cases (e.g. connection is established but authentication fails), or when old-style YAML configuration is present.

The fix is probably:
 - Ensure that hyperion-py clients are disconnected in all cases in Home Assistant.
 - Update hyperion-py documentation to warn that this log entry may reflect a missing `async_client_disconnect()` call.

**Comment by dermotduffy** [comment]
Documentation update:
    * https://github.com/dermotduffy/hyperion-py/commit/41ac46b2f073d48d3b182df95228cd915769d73d
    * https://github.com/dermotduffy/hyperion-py/commit/3032155125a3c7676b0859808136202e1e516961
    * https://github.com/dermotduffy/hyperion-py/commit/015de6a22c529282ae78a14edc573a17987edd09

**Comment by dermotduffy** [comment]
Cleanup merged into Home Assistant, and documentation updated. Thank you for the report @starkillerOG.
